version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Amsterdam"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/"
    rebase-strategy: "auto"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Amsterdam"
    cooldown:
      default-days: 7
      semver-major-days: 14
