name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC
  contents: read

env:
  NODE_VERSION: '22'

jobs:
  release:
    name: Release (GH)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Enable Corepack
        run: corepack enable
      - name: Install latest npm
        run: npm install -g npm@latest
      - uses: actions/setup-node@v6
        with:
          registry-url: https://npm.pkg.github.com
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-npm:
    name: Release (NPM)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Enable Corepack
        run: corepack enable
      - name: Install latest npm
        run: npm install -g npm@latest
      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - run: npm publish
